### ISSUE TITLE
Please consider joining stackage

### ISSUE THREAD

**Issue by nomeata** [byorgey/BlogLiterately#18]
Hi,

distribution package maintenance is much easier if there is a large set of packages that are consistent in their dependency choice. This is precisely what Stackage provides. It would help us (the Debian maintainers) a lot if you would add your package to stackage. http://www.stackage.org/authors explains how that works. The benefit for you is additional QA and notifications if one of your dependencies has upgraded.

Thanks,
Joachim

**Comment by DanBurton** [comment]
+1. I haven't written to my blog in a long time, and my old BlogLiterately executable broke because I deleted the hsenv that it came from. 

```
/home/dan/.hsenv_scratch/cabal/share/x86_64-linux-ghc-7.8.3/pandoc-citeproc-0.3.1/chicago-author-date.csl: openBinaryFile: does not exist (No such file or directory
```

So I went to rebuild it, but unfortunately `BlogLiterately` doesn't build against LTS Haskell, so I can't reuse all of those dependencies I've already installed.

I was able to build it in its own sandbox, but I had to wait for every. single. dependency to install. Whether you choose to join Stackage or not, it would be nice if you could at least be buildable with Stackage versions of dependencies.

**Comment by byorgey** [comment]
Thanks for the pokes.  I do plan to add `BlogLiterately` to Stackage.  Unfortunately, at the moment I am struggling to get `BlogLiterately` to work at all, which is why I have not updated it.  Wordpress changed to only allow XMLRPC calls via https, so I am trying to upgrade haxr to support https.  But I suppose I could still upload an updated version of `BlogLiterately` which at least could be used for converting blog posts to HTML even if it cannot be used to upload to Wordpress right now.

**Comment by byorgey** [comment]
I just realized (I had forgotten) that `BlogLiterately` *was* on Stackage, but had been temporarily removed due to my delinquency in updating it.  I have now uploaded `BlogLiterately-0.7.1.8` which builds with the latest everything, and it should be back in Stackage soon.  It still does not work to upload posts to wordpress, but at least it can be used to generate HTML (or perhaps to upload to other blog platforms, I am not sure).
